import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        fetch: "readonly",
        navigator: "readonly",
        Audio: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        URL: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Event: "readonly",
        MutationObserver: "readonly",
        requestAnimationFrame: "readonly",
        module: "readonly",
        chrome: "readonly",
        CONFIG: "writable",
        MagicRain: "writable",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "warn",
      "no-console": "off",
      "no-redeclare": "off",
      "no-useless-assignment": "warn",
    },
  },
  {
    ignores: ["node_modules/**", "eslint.config.mjs"],
  },
];
